### ISSUE TITLE
Unexpected error (35010) in SOLIDWORKS

### ISSUE THREAD

**Issue by kaz4ikeda** [cristianbuse/VBA-UserForm-MouseScroll#41] opened 2024-05-10 15:36 UTC
As always, I simply put MouseScroll and MouseOverControl  into my SOLIDWORKS (SW) macros and added `EnableMouseScroll Me` in UserForm_Initilalize.
After that I sometimes (not every time) get the compilation error 35010 right after I run the  macros.
The macros are a file-conversion macro which is rather complicated and a simple open-drawing macro.
Some symptoms are:
- SW session is never influenced (such as crash) by this error. Only the macro fails to run .
- If the macro successfully start at first time, the error 35010 seems not to appear thereafter in the SW session.

I think discovered the following workarounds:
- In the file-conversion macro,  removing `Option Explicit` in MouseScroll and MouseOverControl seems to be in effect to reduce occurrence of the error.
- In the open-drawing macro, removing `Option Explicit` in UserForm code-behind stops the error to occur even after once the error occurs. Resuming `Option Explicit` generate the error again.
 
This issue may be closely related to [Issue #27](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/27), but the symptom is slightly different, so I open it as a separate issue.

This error has a random nature and I can't control the occurrence, but I hope some insight will be obtained.

**Comment by cristianbuse** [comment] 2024-05-10 16:20
Could possibly be related to [this](https://answers.microsoft.com/en-us/msoffice/forum/all/word-vba-compile-and-crashing-problems/dd599a63-28ba-4f7b-a6d7-98718cefa3bf)

Could you check the VBA version? In the VBA IDE (VBE) go to **Help** and then **About Visual Basic for Applications 7.1**
Mine looks like this:
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/23198997/1c63f32e-ad82-4143-be3f-dbdad35b0e5a)

It seems 1131 is the trouble version while others say that this has been fixed in version 1133.

Not sure if this is relevant for SOLIDWORKS though

**Comment by cristianbuse** [comment] 2024-05-10 16:27
Could you please add one line to the ```GetCallbackPtr``` method and then test? Simply change this:
```VBA
Private Function GetCallbackPtr() As LongPtr
    Dim ptr As LongPtr: ptr = VBA.Int(AddressOf MouseProc)
```
to this:
```VBA
Private Function GetCallbackPtr() As LongPtr
    Sin 1 'Dummy call to force compiler to 'see' the correct address
    Dim ptr As LongPtr: ptr = VBA.Int(AddressOf MouseProc)
```

**Comment by kaz4ikeda** [comment] 2024-05-10 16:39
I can use SOLIDWORKS only in my office.
I will try your suggestion on Monday and report the results.

My VBA version at home is 1136:
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/9adb8236-c106-4f58-86d1-e13755af62a2)
and I've never seen the error 35010 at home.

**Comment by kaz4ikeda** [comment] 2024-05-13 10:01
VBA version of SW is 1096 (embedded in SW):
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/1905910c-7075-465a-952e-ebb885f3a8c2)

VBA version of Excel is 1128:
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/43b0cbb5-3e14-4a2b-8cdf-8d29b27884a3)

Both of them are before `1133.`

The error 35010 occured when I used the file-conversion macro even the `Sin 1` line is inserted beforehand.
I clicked OK button, then VBA editor showed the following line:
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/15ceeccf-7fe5-443c-b466-c3478bb47aff)

Then I stopped the compilation by Reset button.
Restarting the file-conversion macro caused the error again.
Next, I compiled whole code by the compile command in the debug menu.
Then the macro successfully executed.

**Comment by cristianbuse** [comment] 2024-05-13 10:24
Thanks @kaz4ikeda 

Do you have 'Compile on Demand' turned on by any chance, in Options/General?

Also, please try this:
- Add this method to your code: ```Sub DummyMethod(): End Sub```
- Replace ```Sin 1``` with ```DummyMethod```
- Retry file-conversion macro

**Comment by kaz4ikeda** [comment] 2024-05-13 12:52
Yes,  'Compile on Demand' is turned on (as a default setting).
If this option is turned off, another frequently using macro fails to run. This macro is created by the company's SW-managing division and password protected. Maybe It has a coding mistake somewhere in its code.
So I want to go with it turned on, if possible.
(It would be nice if there was a way to turn it off programmatically.)

I will try your additional suggestion tomorrow.

**Comment by cristianbuse** [comment] 2024-05-13 12:58
> If this option is turned off, another frequently using macro fails to run

😆 never heard that before

> I will try your additional suggestion tomorrow.

Thanks!

**Comment by kaz4ikeda** [comment] 2024-05-14 13:58
Hi, @cristianbuse 

The second try also didn't work:
![20240514_1805_00306_Microsoft_Visual_Basic_for_Applications_-_図面オープン2_](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/ef518921-f9e3-441f-b58a-368cdfb4230c)
I also tried resuming `Sin 1` with `DummyMethod` but to no avail. 

Is your intention to correct the alignment of the stack memory?
Any other idea for workaround?

Maybe I should:
ask the SW-managing division member to remove the compile-time bug of the must-use macro and turn on 'Compile on Demand',
or use "debug -> compile" after the error 35010 occurs once every several times of macro run.
But compilation before execution may not be perfect resolution.

**Comment by cristianbuse** [comment] 2024-05-14 15:10
Thanks @kaz4ikeda for testing!

'Compile on Demand' should be off as it leads to many side effects.

What version of SolidWorks are you using?

**Comment by kaz4ikeda** [comment] 2024-05-14 15:22
OK, I will make an effort for 'Compile on Demand' to be off.
SW version is 2023.
I don't know why the version of the embedded VBE7 is somewhat old.

**Comment by kaz4ikeda** [comment] 2024-05-14 22:43
That was my error. SW I'm using is 2022.

**Comment by kaz4ikeda** [comment] 2024-05-16 12:49
Thank you @cristianbuse.
Following your suggestion, I asked them to debug the must-use macro and the work has done today.
Now I'm using SW with VBA macro fully compiled before execution every time.
One minor problem is that it has revealed that VBA editor option is shared with Excel.
So If all users turns 'Compile on Demand' off, hidden bugs of many Excel macro will explode 😆 .

Anyway, I will continue to benefit from your MouseScroll modules hereafter.

**Closed** 2024-05-16 12:50 UTC

**Comment by cristianbuse** [comment] 2024-05-16 12:54
@kaz4ikeda 

> So If all users turns 'Compile on Demand' off, hidden bugs of many Excel macro will explode 😆 .
😆 I know - it's a mess in any other company. I recently rewrote a financial model and got it's execution speed from 2 minutes down to 100 milliseconds. Not to mentioned fixed logic bug that make you doubt humanity 🤣

**Comment by kaz4ikeda** [comment] 2024-05-16 14:00
Wow, drastic speed up!
Using your MemoryTools?

I have been interested in that because one of my macro faced the speed problem of CopyMemory in a subclassing callback function of MonthCalendar API. I regenerate a object from its ObjPtr value and I had to take a workaround using a static object variable to reduce the usage of CopyMemory. The workaround works well but I had to prepare "Clear" method which makes the object Nothing. Remaining static object makes a program unstable.

If I can take some time to rewrite the macro (maybe not soon), I will try your MomoryTools 😃  .

**Comment by cristianbuse** [comment] 2024-05-16 14:28
> Using your MemoryTools?

No. Nothing that advanced. It was just poor quality code, with unnecessary loops, bad logic and lack of knowledge.

> I have been interested in that because one of my macro faced the speed problem of CopyMemory

MemoryTools is only useful if you have many API calls.

> The workaround works well but I had to prepare "Clear" method which makes the object Nothing

MemoryTools has a ```MemObj``` method which dereferences the pointer while keeping a correct reference count.

If the pointer is for a VBA class (i.e. you have a class module for it) then use the WeakReference repository for full safety.

**Comment by kaz4ikeda** [comment] 2024-05-16 14:50
Thanks for the advice! I'll make use of them.

**Comment by mp3-250** [comment] 2025-12-11 11:27
I would like to reopen this issue. We have the same problem with Solidworks 2023. 
Most of the times our VBA macro works fine, but in a complete random fashion the error 35010 comes out.
It happens only the first time the macro is started, likely closing and restarting solidworks makes the error go away somehow.
If our macro is able to start without the error the first time, it can be closed and restarted many times without any issues, but not if it was to fail the first time. I tried to disable compile on demand, but the error came out anyway. Is there a way to debug it and have an idea where its cause is likely located? I am not a professional coder.

**Comment by cristianbuse** [comment] 2025-12-11 11:38
Hi @mp3-250 

This is a compilation issue. Meaning that the code gets re-compiled in some kind of edge case (hence random) and the callback code is tampered with.

I think it would be best to manually allocate executable memory rather than relying on VBA to do the allocation.

I won't be able to look into this until January though. I will leave this open until then.

Thanks!

**Comment by cristianbuse** [comment] 2026-01-08 16:49
@mp3-250 

Please use the latest version of this repository. Once you have the new code in place, go to the top of the module and change: 
```VBA
#Const CompilerError35010 = False
```
to
```VBA
#Const CompilerError35010 = True
```
and let me know if the issue is solved. Thanks!

**Comment by mp3-250** [comment] 2026-01-10 08:46
Thank you, I will test the latest version asap.

I would like to add some additional information you may find interesting.
With SOLIDWORKS 2025 SP5, the next version we are planning to upgrade to in about 4-5 months, the shipped VBA is 

Microsoft Visual Basic for Applications 7.1

version 1135
VBA: retail 7.1.1135
Forms3: 16.0.14332.20611

**Comment by cristianbuse** [comment] 2026-01-10 09:14
Great.

With version 7.1.11.35 you can leave ```#Const CompilerError35010 = False```

**Comment by mp3-250** [comment] 2026-01-19 02:54
So far the error is gone, but I noticed that solidworks crashed upon launching my  macro a couple of times.

Once the macro loaded its UI, but it froze and I had to terminate solidworks.

I am not sure if it is 100% related with this issue, but the timing and frequency seems to overlap this issue.

**Comment by cristianbuse** [comment] 2026-01-19 13:27
Thanks @mp3-250 dor the info!

Unfortunately, there are only a few things I could try and all of them require extensive reverse-engineering of either the VBE dll or something else. I simply won't have time to look into this, at least not in the next few weeks.
